# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=64, verbose_name='call ID generated by twilio')),
                ('status', models.CharField(max_length=32, verbose_name='call status')),
                ('number', models.CharField(max_length=15, verbose_name='phone number called')),
                ('in_progress', models.BooleanField(default=True)),
            ],
        ),
    ]
